version: '2'
services:
  wotcollector:
    build: .
    depends_on:
      - prom
    expose:
      - "8000"
    ports:
      - "8000:8000"
    environment:
      WOT_ENDPOINTS: 'https://192.168.1.155:8484'
      WOT_VERIFY_SSL: 'False'
      WOT_TOKEN: 'cKXRTaRylYWQiF3MICaKndG4WJMcVLFz'
  prom:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - "9090"
    ports:
      - "9090:9090"
